name: Auto Version Bump, Build, and Release Electron App

on:
  push:
    branches:
      - main # Runs on push to the main branch

jobs:
  bump-version-and-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Bump version
        id: bump_version
        run: |
          # Automatically increment the version (you can change this to minor or major if needed)
          yarn version --patch --no-git-tag-version

          # Capture the new version and store it in the output variable
          $new_version = (Get-Content ./package.json | ConvertFrom-Json).version
          echo "::set-output name=VERSION::$new_version"

          # Commit the version bump
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "ci: bump version to $new_version"
          git push origin main
        shell: pwsh

      - name: Create Tag
        id: tag_check
        run: |
          git tag -a "${{ steps.bump_version.outputs.VERSION }}" -m "Release version ${{ steps.bump_version.outputs.VERSION }}"
          git push origin "${{ steps.bump_version.outputs.VERSION }}"

      - name: Build Electron App
        run: yarn build:win # Adjust this command for your platform

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.*
          tag_name: "${{ steps.bump_version.outputs.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
